const TAGS_PT_ES = {
  CC: "Conjunción coordinada",
  CD: "Número cardinal",
  DT: "Determinante",
  EX: "Existencial",
  FW: "Palabra extranjera",
  IN: "Preposición o conjunción subordinante",
  JJ: "Adjetivo",
  JJR: "Adjetivo comparativo",
  JJS: "Adjetivo superlativo",
  LS: "Marcador de elemento de lista",
  MD: "Verbo modal",
  NN: "Sustantivo, singular o masa",
  NNS: "Sustantivo, plural",
  NNP: "Nombre propio, singular",
  NNPS: "Nombre propio, plural",
  PDT: "Predeterminante",
  POS: "Sufijo posesivo",
  PRP: "Pronombre personal",
  PRP$: "Pronombre posesivo",
  RB: "Adverbio",
  RBR: "Adverbio comparativo",
  RBS: "Adverbio superlativo",
  RP: "Partícula",
  SYM: "Símbolo",
  TO: "a",
  UH: "Interjección",
  VB: "Verbo, forma base",
  VBD: "Verbo, pasado",
  VBG: "Verbo, gerundio o participio presente",
  VBN: "Verbo, participio pasado",
  VBP: "Verbo, presente no tercera persona del singular",
  VBZ: "Verbo, tercera persona del singular presente",
  WDT: "Wh-determinante",
  WP: "Wh-pronombre",
  WP$: "Wh-pronombre posesivo",
  WRB: "Wh-adverbio",
};

const TAGS_PT_DE = {
  CC: "Koordinierende Konjunktion",
  CD: "Kardinalzahl",
  DT: "Determinierer",
  EX: "Existenziell dort",
  FW: "Fremdwort",
  IN: "Präposition oder subordinierende Konjunktion",
  JJ: "Adjektiv",
  JJR: "Adjektiv, vergleichend",
  JJS: "Adjektiv, superlativ",
  LS: "Listenelement-Marker",
  MD: "Modalverb",
  NN: "Substantiv, Singular oder Masse",
  NNS: "Substantiv, Plural",
  NNP: "Eigennamen, Singular",
  NNPS: "Eigennamen, Plural",
  PDT: "Prädeterminierer",
  POS: "Possessiver Endung",
  PRP: "Persönliches Fürwort",
  PRP$: "Possessives Fürwort",
  RB: "Adverb",
  RBR: "Adverb, vergleichend",
  RBS: "Adverb, superlativ",
  RP: "Partikel",
  SYM: "Symbol",
  TO: "zu",
  UH: "Interjektion",
  VB: "Verb, Grundform",
  VBD: "Verb, Vergangenheitsform",
  VBG: "Verb, Gerundium oder Partizip Präsens",
  VBN: "Verb, Partizip Perfekt",
  VBP: "Verb, nicht 3. Person Singular Präsens",
  VBZ: "Verb, 3. Person Singular Präsens",
  WDT: "Wh-Determinierer",
  WP: "Wh-Pronomen",
  WP$: "Possessives Wh-Pronomen",
  WRB: "Wh-Adverb",
};

const TAGS_PT_EN = {
  CC: "Coordinating conjunction",
  CD: "Cardinal number",
  DT: "Determiner",
  EX: "Existential there",
  FW: "Foreign word",
  IN: "Preposition or subordinating conjunction",
  JJ: "Adjective",
  JJR: "Adjective, comparative",
  JJS: "Adjective, superlative",
  LS: "List item marker",
  MD: "Modal",
  NN: "Noun, singular or mass",
  NNS: "Noun, plural",
  NNP: "Proper noun, singular",
  NNPS: "Proper noun, plural",
  PDT: "Predeterminer",
  POS: "Possessive ending",
  PRP: "Personal pronoun",
  PRP$: "Possessive pronoun",
  RB: "Adverb",
  RBR: "Adverb, comparative",
  RBS: "Adverb, superlative",
  RP: "Particle",
  SYM: "Symbol",
  TO: "to",
  UH: "Interjection",
  VB: "Verb, base form",
  VBD: "Verb, past tense",
  VBG: "Verb, gerund or present participle",
  VBN: "Verb, past participle",
  VBP: "Verb, non-3rd person singular present",
  VBZ: "Verb, 3rd person singular present",
  WDT: "Wh-determiner",
  WP: "Wh-pronoun",
  WP$: "Possessive wh-pronoun",
  WRB: "Wh-adverb",
};

const TAGS_PT_DESCRIPTION_ES = {
  CC: "Conjunción de coordinación: conecta palabras o grupos de palabras de manera similar, expresando relación de coordinación.",
  CD: "Número cardinal: representa números que indican cantidad o posición en una secuencia.",
  DT: "Determinante: introduce un sustantivo y especifica o cuantifica su alcance.",
  EX: "Existencial: indica la existencia de algo o alguien.",
  FW: "Palabra extranjera: representa palabras provenientes de idiomas extranjeros.",
  IN: "Preposición o conjunción subordinante: introduce una relación espacial, temporal u otra relación lógica.",
  JJ: "Adjetivo: describe o califica un sustantivo o pronombre.",
  JJR: "Adjetivo comparativo: compara dos sustantivos indicando que uno posee una cualidad en mayor medida que el otro.",
  JJS: "Adjetivo superlativo: indica que un sustantivo posee una cualidad en mayor medida que cualquier otro de su tipo.",
  LS: "Marcador de ítem de lista: indica el comienzo de un elemento de lista en un contexto de lista.",
  MD: "Modal: indica la actitud del hablante hacia la acción expresada por el verbo.",
  NN: "Sustantivo, singular o incontable: representa nombres de objetos, lugares, personas o conceptos.",
  NNS: "Sustantivo, plural: representa nombres de objetos, lugares, personas o conceptos en forma plural.",
  NNP: "Sustantivo propio, singular: representa nombres propios de personas, lugares u organizaciones en forma singular.",
  NNPS: "Sustantivo propio, plural: representa nombres propios de personas, lugares u organizaciones en forma plural.",
  PDT: "Predeterminante: introduce un sustantivo y generalmente precede a un artículo.",
  POS: "Posesivo: indica posesión y generalmente se agrega al final de un sustantivo.",
  PRP: "Pronombre personal: reemplaza a un sustantivo y se refiere a una persona, animal, cosa o concepto.",
  PRP$: "Pronombre posesivo: indica posesión y se refiere a la posesión de un sustantivo.",
  RB: "Adverbio: modifica un verbo, un adjetivo o otro adverbio, proporcionando información adicional sobre la manera, lugar, tiempo, cantidad, entre otros.",
  RBR: "Adverbio comparativo: compara la manera en que se realiza una acción, indicando que algo se hace en mayor medida que otra cosa.",
  RBS: "Adverbio superlativo: indica que algo se realiza en mayor medida que cualquier otra cosa de su tipo.",
  RP: "Partícula: palabras que no pertenecen a ninguna de las categorías principales y se utilizan para expresar diversas funciones gramaticales.",
  SYM: "Símbolo: representa símbolos, signos o caracteres especiales.",
  TO: "a, para: se utiliza como parte de la construcción 'to + verbo' para expresar la dirección, el objetivo o el propósito de una acción.",
  UH: "Interjección: expresa una emoción, sorpresa, exclamación o llamada.",
  VB: "Verbo, forma base: representa la forma base de un verbo sin conjugación específica.",
  VBD: "Verbo, pasado: representa la forma pasada de un verbo.",
  VBG: "Verbo, gerundio o participio presente: representa la forma en -ing de un verbo, que puede funcionar como gerundio o participio presente.",
  VBN: "Verbo, participio pasado: representa la forma pasada de un verbo que se utiliza como participio pasado.",
  VBP: "Verbo, presente no tercera persona singular: representa la forma en presente de un verbo en primera o segunda persona, o en tercera persona plural.",
  VBZ: "Verbo, presente tercera persona singular: representa la forma en presente de un verbo en tercera persona singular.",
  WDT: "Determinante interrogativo: introduce preguntas que requieren una respuesta con información específica.",
  WP: "Pronombre interrogativo: se utiliza para formular preguntas directas o indirectas.",
  WP$: "Pronombre posesivo interrogativo: indica posesión en preguntas interrogativas.",
  WRB: "Adverbio interrogativo: introduce preguntas y modifica un verbo, un adjetivo o un adverbio.",
};

const TAGS_ES = {
  ADJA: "Adjetivo atributivo",
  ADJD: "Adjetivo predicativo",
  ADV: "Adverbio",
  APPR: "Preposición; Circunposición a la izquierda",
  APPRART: "Preposición con artículo",
  APPO: "Posposición",
  APZR: "Circunposición a la derecha",
  ART: "Artículo definido O indefinido",
  CARD: "Número cardinal",
  FM: "Material en lengua extranjera",
  ITJ: "Interjección",
  KOUI: "Conjunción subordinada con (para) infinitivo",
  KOUS: "Conjunción subordinada",
  KON: "Conjunción coordinada Y, O, Pero",
  KOKOM: "Conjunción comparativa Como, Que",
  NN: "Sustantivo normal",
  NE: "Nombres propios",
  PDAT: "Pronombre demostrativo atributivo",
  PDS: "Pronombre demostrativo sustituto",
  PIAT: "Pronombre indefinido atributivo",
  PIS: "Pronombre indefinido sustituto",
  PPER: "Pronombre personal (no reflexivo)",
  PPOSAT: "Pronombre posesivo atributivo",
  PPOSS: "Pronombre posesivo sustituto",
  PRELS: "Pronombre relativo sustituto",
  PRELAT: "Pronombre relativo atributivo",
  PRF: "Pronombre reflexivo",
  PWS: "Pronombre interrogativo sustituto",
  PWAT: "Pronombre interrogativo atributivo",
  PWAV: "Pronombre interrogativo adverbial",
  PROAV: "Pronominal adverbial",
  PTKZU: '"Zu" antes de infinitivo',
  PTKNEG: "Partícula de negación No",
  PTKVZ: "Prefijo verbal separado/partícula verbal",
  PTKANT: "Partícula de respuesta",
  PTKA: 'Partícula "Am" o "Zu" antes de adjetivo o adverbio',
  TRUNC: "Prefijo de composición separado",
  VVFIN: "Verbo finito",
  VAFIN: "Verbo finito o verbo de cópula",
  VMFIN: "Verbo modal finito",
  VVINF: "Verbo infinito",
  VAINF: "Verbo auxiliar o verbo de cópula infinito",
  VMINF: "Verbo modal infinito",
  VVIMP: "Imperativo",
  VAIMP: "Verbo de cópula en imperativo",
  VVPP: "Verbo en participio (Participio II)",
  VAPP: "Verbo auxiliar o verbo de cópula en participio (Participio II)",
  VMPP: "Verbo modal en participio (Participio II)",
  VVIZU: 'Verbo completo/verbo de partícula en infinitivo con "Zu"',
  XY: "No palabra, símbolo o abreviatura",
  "$,": "Coma",
  "$(": "Otra puntuación interna de la oración",
  "$.": "Puntuación que termina la oración",
};

const TAGS_DE = {
  ADJA: "Attributives Adjektiv",
  ADJD: "Prädikatives Adjektiv",
  ADV: "Adverb",
  APPR: "Präposition; Zirkumposition links",
  APPRART: "Präposition mit Artikel",
  APPO: "Postposition",
  APZR: "Zirkumposition rechts",
  ART: "Bestimmter ODER unbestimmter Artikel",
  CARD: "Kardinalzahl",
  FM: "Fremdsprachliches Material",
  ITJ: "Interjektion",
  KOUI: "Unterordnende Konjunktion mit (zu-)Infinitiv",
  KOUS: "Unterordnende Konjunktion",
  KON: "Nebenordnende Konjunktion und, oder, aber",
  KOKOM: "Vergleichskonjunktion als, wie",
  NN: "Normales Nomen",
  NE: "Eigennamen",
  PDAT: "Attribuierendes Demonstrativpronomen",
  PDS: "Substituierendes Demonstrativpronomen",
  PIAT: "Attribuierendes Indefinitpronomen",
  PIS: "Substituierendes Indefinitpronomen",
  PPER: "(nicht-reflexives) Personalpronomen",
  PPOSAT: "Attribuierendes Possessivpronomen",
  PPOSS: "Substituierendes Possessivpronomen",
  PRELS: "Substituierendes Relativpronomen",
  PRELAT: "Attribuierendes Relativpronomen",
  PRF: "Reflexivpronomen",
  PWS: "Substituierendes Interrogativpronomen",
  PWAT: "Attribuierendes Interrogativpronomen",
  PWAV: "Adverbiales Interrogativpronomen",
  PROAV: "Pronominaladverb",
  PTKZU: '"zu" vor Infinitiv',
  PTKNEG: "Negationspartikel nicht",
  PTKVZ: "Abgetrennter Verbzusatz/Verbpartikel",
  PTKANT: "Antwortpartikel",
  PTKA: 'Partikel "am" o. "zu" vor Adjektiv o. Adverb',
  TRUNC: "Abgetrenntes Kompositionserstglied",
  VVFIN: "Finites Vollverb",
  VAFIN: "Finites Voll- oder Kopulaverb",
  VMFIN: "Finites Modalverb",
  VVINF: "Infinites Vollverb",
  VAINF: "Infinites Hilfsverb oder Kopulaverb",
  VMINF: "Infinites Modalverb",
  VVIMP: "Vollverb im Imperativ",
  VAIMP: "Kopulaverb im Imperativ",
  VVPP: "Partizipiales Vollverb (Partizip II)",
  VAPP: "Partizipiales Hilfs-/Kopulaverb (Partizip II)",
  VMPP: "Partizipiales Modalverb (Partizip II)",
  VVIZU: 'Vollverb/Partikelverb im "zu"-Infinitiv',
  XY: "Nichtwort, Sonderzeichen, Kürzel",
  "$,": "Komma",
  "$(": "Sonstige satzinterne Interpunktion",
  "$.": "Satzbeendende Interpunktion",
};

const TAGS_EN = {
  ADJA: "Attributive adjective",
  ADJD: "Predicative adjective",
  ADV: "Adverb",
  APPR: "Preposition; Circumposition (to the left)",
  APPRART: "Preposition with article",
  APPO: "Postposition",
  APZR: "Circumposition (to the right)",
  ART: "Definite or indefinite article",
  CARD: "Cardinal number",
  FM: "Foreign language material",
  ITJ: "Interjection",
  KOUI: "Subordinating conjunction with (to-)infinitive",
  KOUS: "Subordinating conjunction",
  KON: "Coordinating conjunction and, or, but",
  KOKOM: "Comparative conjunction as, like",
  NN: "Normal noun",
  NE: "Proper noun",
  PDAT: "Attributive demonstrative pronoun",
  PDS: "Substituting demonstrative pronoun",
  PIAT: "Attributive indefinite pronoun",
  PIS: "Substituting indefinite pronoun",
  PPER: "(Non-reflexive) personal pronoun",
  PPOSAT: "Attributive possessive pronoun",
  PPOSS: "Substituting possessive pronoun",
  PRELS: "Substituting relative pronoun",
  PRELAT: "Attributive relative pronoun",
  PRF: "Reflexive pronoun",
  PWS: "Substituting interrogative pronoun",
  PWAT: "Attributive interrogative pronoun",
  PWAV: "Adverbial interrogative pronoun",
  PROAV: "Pronominal adverb",
  PTKZU: '"zu" before infinitive',
  PTKNEG: "Negation particle not",
  PTKVZ: "Separated verb prefix/particle",
  PTKANT: "Answer particle",
  PTKA: 'Particle "am" or "zu" before adjective or adverb',
  TRUNC: "Separated compound first element",
  VVFIN: "Finite full verb",
  VAFIN: "Finite full or copula verb",
  VMFIN: "Finite modal verb",
  VVINF: "Infinite full verb",
  VAINF: "Infinite auxiliary or copula verb",
  VMINF: "Infinite modal verb",
  VVIMP: "Imperative full verb",
  VAIMP: "Imperative copula verb",
  VVPP: "Participial full verb (Participle II)",
  VAPP: "Participial auxiliary/copula verb (Participle II)",
  VMPP: "Participial modal verb (Participle II)",
  VVIZU: 'Full verb/particle verb in "zu"-infinitive',
  XY: "Non-word, special character, abbreviation",
  "$,": "Comma",
  "$(": "Other sentence-internal punctuation",
  "$.": "Sentence-ending punctuation",
};

const TAGS_DESCRIPTION_ES = {
  ADJA: "Adjetivo atributivo: se utiliza para marcar adjetivos que modifican a un sustantivo de manera atributiva, es decir, directamente vinculados al sustantivo y cumpliendo la función de describir sus características.",
  ADJD: "Adjetivo predicativo: se aplica a adjetivos que funcionan de manera predicativa, es decir, describiendo las características de un sustantivo de manera más amplia en relación con el contexto de la oración.",
  ADV: "Adverbio: se utiliza para marcar palabras que modifican o describen un verbo, un adjetivo u otro adverbio, proporcionando información adicional sobre la manera, el lugar, el tiempo, la frecuencia, entre otros.",
  APPR: "Preposición; Circunposición a la izquierda: se aplica a preposiciones que se colocan antes de su complemento, indicando la relación entre el complemento y otra palabra en la oración. También se utiliza para circunposiciones a la izquierda que constan de dos partes separadas.",
  APPRART:
    "Preposición con artículo: se utiliza para preposiciones que llevan un artículo junto a ellas. Indica una relación espacial o temporal entre dos elementos en la oración.",
  APPO: "Posposición: se aplica a palabras que se colocan después de su complemento y establecen una relación con otra palabra en la oración. Indica la relación espacial o temporal entre los elementos.",
  APZR: "Circunposición a la derecha: se utiliza para circunposiciones que constan de dos partes separadas, siendo la segunda parte una preposición que sigue a su complemento.",
  ART: "Artículo definido O indefinido: se aplica a artículos, que son palabras que preceden a un sustantivo para indicar si se refieren a un objeto específico o no.",
  CARD: "Número cardinal: se utiliza para marcar números cardinales, que indican cantidad o posición en una secuencia.",
  FM: "Material en lengua extranjera: se aplica a palabras o fragmentos de texto en una lengua extranjera, indicando que no pertenecen al idioma principal del texto.",

  ITJ: "Interjección: se utiliza para marcar palabras que expresan emociones, sentimientos o exclamaciones de manera independiente, sin estar vinculadas gramaticalmente a otras palabras en la oración.",
  KOUI: "Conjunción subordinada con (para) infinitivo: se aplica a conjunciones subordinadas que introducen una cláusula subordinada con un infinitivo y establecen una relación de dependencia con la oración principal.",
  KOUS: "Conjunción subordinada: se utiliza para conjunciones que introducen cláusulas subordinadas, indicando una relación de dependencia con la oración principal.",
  KON: "Conjunción coordinada Y, O, Pero: se aplica a conjunciones coordinadas que conectan palabras, frases o cláusulas de manera equivalente o contrastante.",
  KOKOM:
    "Conjunción comparativa Como, Que: se utiliza para conjunciones que introducen una cláusula comparativa, estableciendo una relación de comparación entre dos elementos.",
  NN: "Sustantivo normal: se aplica a sustantivos que cumplen la función de nombres comunes, es decir, no son nombres propios.",
  NE: "Nombres propios: se utiliza para marcar sustantivos que son nombres propios, es decir, nombres específicos de personas, lugares u objetos.",
  PDAT: "Pronombre demostrativo atributivo: se aplica a pronombres demostrativos que funcionan como adjetivos y modifican a un sustantivo de manera atributiva.",
  PDS: "Pronombre demostrativo sustituto: se utiliza para pronombres demostrativos que sustituyen a un sustantivo en la oración, indicando su posición o identidad en el contexto.",

  PIAT: "Pronombre indefinido atributivo: se aplica a pronombres indefinidos que funcionan como adjetivos y modifican a un sustantivo de manera atributiva.",
  PIS: "Pronombre indefinido sustituto: se utiliza para pronombres indefinidos que sustituyen a un sustantivo en la oración, indicando su posición o identidad en el contexto.",
  PPER: "Pronombre personal (no reflexivo): se aplica a pronombres personales que no tienen función reflexiva, es decir, no se refieren al sujeto de la misma oración.",
  PPOSAT:
    "Pronombre posesivo atributivo: se utiliza para pronombres posesivos que funcionan como adjetivos y modifican a un sustantivo de manera atributiva.",
  PPOSS:
    "Pronombre posesivo sustituto: se aplica a pronombres posesivos que sustituyen a un sustantivo en la oración, indicando la posesión en el contexto.",
  PRELS:
    "Pronombre relativo sustituto: se utiliza para pronombres relativos que sustituyen a un sustantivo en la oración, introduciendo una cláusula relativa que describe o identifica al sustantivo.",
  PRELAT:
    "Pronombre relativo atributivo: se aplica a pronombres relativos que funcionan como adjetivos y modifican a un sustantivo de manera atributiva.",
  PRF: "Pronombre reflexivo: se utiliza para marcar pronombres que se refieren al sujeto de la misma oración, indicando que la acción recae sobre el propio sujeto.",
  PWS: "Pronombre interrogativo sustituto: se aplica a pronombres interrogativos que sustituyen a un sustantivo en la oración, indicando su posición o identidad en el contexto.",

  PWAT: "Pronombre interrogativo atributivo: se aplica a pronombres interrogativos que funcionan como adjetivos y modifican a un sustantivo de manera atributiva.",
  PWAV: "Pronombre interrogativo adverbial: se utiliza para pronombres interrogativos que tienen la función de un adverbio en la oración, modificando un verbo, adjetivo u otro adverbio.",
  PROAV:
    "Pronominal adverbial: se aplica a pronombres que funcionan como adverbios en la oración, proporcionando información adicional sobre el verbo, adjetivo u otro adverbio.",
  PTKZU:
    '"Zu" antes de infinitivo: indica la presencia de la partícula "zu" seguida de un verbo en infinitivo, denotando una construcción verbal específica.',
  PTKNEG:
    "Partícula de negación 'No': se utiliza para marcar la presencia de la partícula de negación 'no' en la oración, indicando la negación de la acción o el estado.",
  PTKVZ:
    "Prefijo verbal separado/partícula verbal: se aplica a prefijos verbales separados o partículas verbales que modifican el significado del verbo al que están asociados.",
  PTKANT:
    "Partícula de respuesta: se utiliza para marcar la presencia de una partícula que introduce o responde a una pregunta o declaración en la oración.",
  PTKA: 'Partícula "Am" o "Zu" antes de adjetivo o adverbio: indica la presencia de la partícula "am" o "zu" seguida de un adjetivo o adverbio, modificando su significado.',
  TRUNC:
    "Prefijo de composición separado: se aplica a prefijos de composición que están separados del resto de la palabra y que modifican el significado del lexema al que se adjuntan.",

  VVFIN:
    "Verbo finito: se aplica a verbos que funcionan como el verbo principal de la oración y están conjugados de acuerdo con el sujeto y el tiempo.",
  VAFIN:
    "Verbo finito o verbo de cópula: se utiliza para verbos que pueden funcionar como el verbo principal de la oración (finito) o como un verbo de cópula, conectando el sujeto con un atributo o predicado nominal.",
  VMFIN:
    "Verbo modal finito: se aplica a verbos modales que están conjugados de acuerdo con el sujeto y el tiempo.",
  VVINF:
    "Verbo infinito: se utiliza para verbos en su forma base, sin conjugación de acuerdo con el sujeto o el tiempo. Pueden desempeñar funciones de sustantivo, adjetivo o adverbio.",
  VAINF:
    "Verbo auxiliar o verbo de cópula infinito: se aplica a verbos auxiliares o verbos de cópula en su forma base, sin conjugación de acuerdo con el sujeto o el tiempo.",
  VMINF:
    "Verbo modal infinito: se utiliza para verbos modales en su forma base, sin conjugación de acuerdo con el sujeto o el tiempo.",
  VVIMP:
    "Imperativo: se aplica a verbos que expresan órdenes, mandatos o solicitudes directas. Se utilizan en situaciones en las que se desea influir en la acción del hablante.",
  VAIMP:
    "Verbo de cópula en imperativo: se aplica a verbos de cópula que se utilizan en imperativos, conectando el sujeto con un atributo o predicado nominal en situaciones de orden o solicitud directa.",
  VVPP: "Verbo en participio (Participio II): se utiliza para indicar la forma de participio pasado de un verbo, que se puede utilizar para formar tiempos compuestos y pasivas.",

  VAPP: "Verbo auxiliar o verbo de cópula en participio (Participio II): se aplica a verbos auxiliares o verbos de cópula en su forma de participio pasado, que se utiliza para formar tiempos compuestos y pasivas.",
  VMPP: "Verbo modal en participio (Participio II): se utiliza para indicar la forma de participio pasado de un verbo modal, que se puede utilizar para formar tiempos compuestos y expresar modalidad.",
  VVIZU:
    'Verbo completo/verbo de partícula en infinitivo con "Zu": se aplica a verbos compuestos en alemán que están formados por un verbo principal y una partícula, y se encuentran en su forma infinitiva junto con la partícula "Zu".',
  XY: "No palabra, símbolo o abreviatura: se utiliza para elementos que no son palabras, símbolos o abreviaturas en el contexto del análisis gramatical.",
  "$,": "Coma: se aplica a comas, que son signos de puntuación utilizados para separar elementos en una oración.",
  "$(": "Otra puntuación interna de la oración: se utiliza para otros signos de puntuación interna en una oración, excluyendo comas y puntos finales.",
  "$.": "Puntuación que termina la oración: se aplica a signos de puntuación, como puntos finales, que indican el final de una oración.",
};

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const _availables = {
  TAGS_PT_ES,
  TAGS_PT_DE,
  TAGS_PT_EN,
  TAGS_PT_DESCRIPTION_ES,
  TAGS_ES,
  TAGS_DE,
  TAGS_EN,
  TAGS_DESCRIPTION_ES,
};

export default {
  es: { ...TAGS_PT_DESCRIPTION_ES, ...TAGS_DESCRIPTION_ES },
  de: { ...TAGS_PT_DE, ...TAGS_DE },
  en: { ...TAGS_PT_EN, ...TAGS_EN },
};
