const UniversalFeatures_DESCRIPTION_ES = {
  Animacy: {
    Anim: "Animado: Seres vivos con movimiento propio.",
    Hum: "Humano: Relativo a los humanos.",
    Inan: "Inanimado: No vivo, carece de movimiento propio.",
    Nhum: "No humano: No relacionado con los humanos.",
  },
  Aspect: {
    Hab: "Habitual: Expresa acción repetida o costumbre.",
    Imp: "Imperfecto: Acción en curso o continua.",
    Perf: "Perfecto: Acción completada con relevancia en el presente.",
    Prog: "Progresivo: Acción en progreso en un momento específico.",
  },
  Case: {
    Abe: "Ablativo: Movimiento hacia afuera.",
    Acc: "Acusativo: Objeto directo de un verbo transitivo.",
    Erg: "Ergativo: Sujeto de un verbo transitivo en lenguajes ergativo-absolutivo.",
    Nom: "Nominativo: Sujeto de un verbo.",
    Abs: "Absolutivo: Sujeto de un verbo intransitivo u objeto directo de un verbo transitivo en lenguajes ergativo-absolutivo.",
    Dat: "Dativo: Objeto indirecto de un verbo.",
    Gen: "Genitivo: Indica posesión o asociación.",
    Ins: "Instrumental: Medio mediante el cual se realiza una acción.",
    Loc: "Locativo: Ubicación de la acción.",
    Par: "Partitivo: Parte de un todo.",
    Voc: "Vocativo: Se utiliza para la dirección directa.",
  },
  Definite: {
    Com: "Comitativo: En asociación o compañía.",
    Cons: "Estado constructo: Se utiliza para marcar un sustantivo poseído en estado constructo.",
    Def: "Definido: Específico e identificable.",
    Ind: "Indefinido: No específico ni identificable.",
  },
  Degree: {
    Abs: "Absoluto: Forma base de un adjetivo o adverbio.",
    Cmp: "Comparativo: Indica un grado superior en comparación con otro.",
    Equ: "Ecuativo: Indica igualdad.",
    Pos: "Positivo: Forma base de un adjetivo o adverbio.",
    Sup: "Superlativo: Indica el grado más alto.",
  },
  Evident: {
    Fh: "Oído familiar: Información de una fuente familiar.",
    Nfh: "Oído no familiar: Información de una fuente no familiar.",
  },
  Gender: {
    Com: "Común: Sin distinción de género específico.",
    Fem: "Femenino: Die, Género femenino.",
    Masc: "Masculino: Der, Género masculino.",
    Neut: "Neutro: Das, Sin género o género neutro. ",
  },
  Mood: {
    Cnd: "Condicional: Dependiente de una condición.",
    Imp: "Imperativo: Orden o solicitud.",
    Ind: "Indicativo: Afirmaciones de hechos.",
    Jus: "Jusivo: Indica una orden o solicitud leve.",
    Sub: "Subjuntivo: Expresa duda, posibilidad, necesidad o acción contraria a los hechos.",
  },
  NumType: {
    Card: "Cardinal: Números que indican cantidad.",
    Dist: "Distributivo: Se refiere a cada miembro de un conjunto.",
    Frac: "Fracción: Números que indican una parte de un todo.",
    Mult: "Multiplicativo: Indica multiplicación.",
    Ord: "Ordinal: Números que indican posición u orden.",
    Range: "Rango: Números que indican un rango de valores.",
    Sets: "Conjuntos: Números que indican conjuntos de cosas.",
  },
  Number: {
    Count: "Contable: Singular o plural según la cantidad.",
    Dual: "Dual: Que se refiere a un par.",
    Grpa: "Paucal mayor: Más que un número paucal.",
    Grpl: "Plural mayor: Más que un número plural.",
    Inv: "Inverso: Indica lo opuesto al número predeterminado.",
    Pauc: "Paucal: Que se refiere a unos pocos.",
    Plur: "Plural: Que se refiere a más de uno.",
    Ptan: "Plurale tantum: Se usa solo en forma plural.",
    Sing: "Singular: Que se refiere a uno.",
    Tri: "Trial: Que se refiere a tres.",
  },
  Person: {
    "0": "Persona cero: Sin participante.",
    "1": "Primera persona: Hablante o hablantes.",
    "2": "Segunda persona: Oyente o oyentes.",
    "3": "Tercera persona: Alguien o algo que no es el hablante ni el oyente.",
  },
  Polarity: {
    Neg: "Negativo: Indica negación.",
    Pos: "Positivo: Indica afirmación.",
  },
  Politeness: {
    Elev: "Elevado: Registro educado o formal.",
    Form: "Formal: Registro educado o formal.",
    Humb: "Humilde: Registro educado o humilde.",
    Infm: "Informal: Registro informal o casual.",
  },
  Poss: {
    Yes: "Sí: Indica posesión.",
  },
  PronType: {
    Art: "Artículo: Un tipo de determinante.",
    Dem: "Demostrativo: Señala o especifica un sustantivo.",
    Emp: "Enfático: Enfatiza el nominal al que depende.",
    Exc: "Exclamativo: Expresa la sorpresa del hablante.",
    Ind: "Indefinido: Se refiere a un elemento no específico.",
    Int: "Interrogativo: Se utiliza en preguntas.",
    Neg: "Negativo: Expresa negación.",
    Prs: "Personal: Relativo a una persona o cosa.",
    Rcp: "Recíproco: Indica acción o relación mutua.",
    Rel: "Relativo: Introduce una cláusula relativa.",
    Tot: "Total (Colectivo): Se refiere a un grupo o colección completa.",
  },
  Reflex: {
    Yes: "Sí es reflexivo: Indica reflexividad.",
  },
  Tense: {
    Fut: "Futuro: Acción que ocurrirá en el futuro.",
    Past: "Pasado: Acción que ocurrió en el pasado.",
    Pres: "Presente: Acción que ocurre en el momento actual.",
  },
  VerbForm: {
    Conv: "Converbo: Forma de verbo que funciona como una conjunción.",
    Fin: "Finito: Forma verbal que indica tiempo y persona.",
    Inf: "Infinitivo: Forma no finita que no indica tiempo ni persona.",
    Part: "Participio: Forma no finita que puede funcionar como adjetivo o en construcciones verbales.",
  },
  Voice: {
    Act: "Activo: El sujeto realiza la acción.",
    Antip: "Antipasivo: Acción centrada en el objeto con ausencia del agente.",
    Cau: "Causativo: Indica que la acción hace que algo suceda.",
    Dir: "Directo: Acción directa sin mediación.",
    Inv: "Inverso: Indica inversión de roles entre sujeto y objeto.",
    Mid: "Medio: La acción afecta reflexivamente al sujeto.",
    Pass: "Pasivo: El sujeto es afectado por la acción del verbo.",
    Rcp: "Recíproco: Indica una acción o relación mutua.",
    Ref: "Reflexivo: Sujeto y objeto son iguales.",
    Spont:
      "Espontáneo: Acción que ocurre espontáneamente o sin una causa conocida.",
  },
  Foreign: {
    Yes: "Palabra extranjera",
  },
};

const UniversalFeatures_DESCRIPTION_DE = {
  Animacy: {
    Anim: "Belebt: Lebewesen mit Eigendynamik.",
    Hum: "Mensch: Bezieht sich auf Menschen.",
    Inan: "Unbelebt: Nicht lebendig, ohne Eigendynamik.",
    Nhum: "Nicht-menschlich: Nicht mit Menschen verbunden.",
  },
  Aspect: {
    Hab: "Gewohnheitsmäßig: Drückt wiederholte oder gewohnheitsmäßige Handlungen aus.",
    Imp: "Imperfekt: Andauernde oder fortlaufende Handlung.",
    Perf: "Perfekt: Abgeschlossene Handlung mit Bezug zur Gegenwart.",
    Prog: "Progressiv: Handlung in Fortschritt zu einem bestimmten Zeitpunkt.",
  },
  Case: {
    Abe: "Ablativ: Bewegung weg von etwas.",
    Acc: "Akkusativ: Direktes Objekt eines transitiven Verbs.",
    Erg: "Ergativ: Subjekt eines transitiven Verbs in ergativ-absoluten Sprachen.",
    Nom: "Nominativ: Subjekt eines Verbs.",
    Abs: "Absolutiv: Subjekt eines intransitiven Verbs oder direktes Objekt eines transitiven Verbs in ergativ-absoluten Sprachen.",
    Dat: "Dativ: Indirektes Objekt eines Verbs.",
    Gen: "Genitiv: Kennzeichnet Besitz oder Zugehörigkeit.",
    Ins: "Instrumental: Mittel, durch das eine Handlung ausgeführt wird.",
    Loc: "Lokativ: Ort der Handlung.",
    Par: "Partitiv: Teil eines Ganzen.",
    Voc: "Vokativ: Wird für direkte Anrede verwendet.",
  },
  Definite: {
    Com: "Begleitend: In Verbindung oder Begleitung.",
    Cons: "Konstruktzustand: Markiert ein besessenes Substantiv im konstruktiven Zustand.",
    Def: "Bestimmt: Spezifisch und identifizierbar.",
    Ind: "Unbestimmt: Nicht spezifisch oder identifizierbar.",
  },
  Degree: {
    Abs: "Absolut: Grundform eines Adjektivs oder Adverbs.",
    Cmp: "Komparativ: Zeigt einen höheren Grad im Vergleich zu einem anderen.",
    Equ: "Äquativ: Zeigt Gleichheit an.",
    Pos: "Positiv: Grundform eines Adjektivs oder Adverbs.",
    Sup: "Superlativ: Zeigt den höchsten Grad an.",
  },
  Evident: {
    Fh: "Vertraute Überlieferung: Informationen aus einer vertrauten Quelle.",
    Nfh: "Unvertraute Überlieferung: Informationen aus einer unbekannten Quelle.",
  },
  Gender: {
    Com: "Gemeinsam: Keine spezifische Geschlechtsunterscheidung.",
    Fem: "Feminin: Die, Weibliches Geschlecht.",
    Masc: "Maskulin: Der, Männliches Geschlecht.",
    Neut: "Neutral: Das, Kein Geschlecht oder neutrales Geschlecht.",
  },
  Mood: {
    Cnd: "Konditional: Abhängig von einer Bedingung.",
    Imp: "Imperativ: Befehl oder Bitte.",
    Ind: "Indikativ: Aussagen von Tatsachen.",
    Jus: "Jussiv: Gibt einen milden Befehl oder eine Bitte an.",
    Sub: "Konjunktiv: Drückt Zweifel, Möglichkeit, Notwendigkeit oder Handlung im Widerspruch zur Tatsache aus.",
  },
  NumType: {
    Card: "Kardinal: Zahlen, die die Menge anzeigen.",
    Dist: "Distributiv: Bezieht sich auf jedes Mitglied in einer Menge.",
    Frac: "Fraktion: Zahlen, die einen Teil einer Ganzheit anzeigen.",
    Mult: "Multiplikativ: Zeigt Multiplikation an.",
    Ord: "Ordinal: Zahlen, die Position oder Reihenfolge anzeigen.",
    Range: "Bereich: Zahlen, die einen Bereich von Werten anzeigen.",
    Sets: "Sets: Zahlen, die Mengen von Dingen anzeigen.",
  },
  Number: {
    Count: "Zählung: Singular oder Plural je nach Menge.",
    Dual: "Dual: Bezieht sich auf ein Paar.",
    Grpa: "Größere Paucal: Mehr als eine paucale Anzahl.",
    Grpl: "Größere Mehrzahl: Mehr als eine Mehrzahl.",
    Inv: "Inverse: Zeigt das Gegenteil der Standardanzahl an.",
    Pauc: "Paucal: Bezieht sich auf einige wenige.",
    Plur: "Mehrzahl: Bezieht sich auf mehr als eine.",
    Ptan: "Plurale tantum: Wird nur in der Pluralform verwendet.",
    Sing: "Singular: Bezieht sich auf eins.",
    Tri: "Trial: Bezieht sich auf drei.",
  },
  Person: {
    "0": "Nullte Person: Kein Teilnehmer.",
    "1": "Erste Person: Sprecher oder Sprecher.",
    "2": "Zweite Person: Zuhörer oder Zuhörer.",
    "3": "Dritte Person: Jemand oder etwas außerhalb des Sprechers oder Zuhörers.",
  },
  Polarity: {
    Neg: "Negativ: Zeigt Verneinung an.",
    Pos: "Positiv: Zeigt Bestätigung an.",
  },
  Politeness: {
    Elev: "Erhoben: Höfliche oder formale Sprache.",
    Form: "Formal: Höfliche oder formale Sprache.",
    Humb: "Bescheiden: Höfliche oder bescheidene Sprache.",
    Infm: "Informell: Informelle oder lockere Sprache.",
  },
  Poss: {
    Yes: "Ja: Zeigt Besitz an.",
  },
  PronType: {
    Art: "Artikel: Eine Art von Determinator.",
    Dem: "Demonstrativ: Zeigt auf oder spezifiziert ein Substantiv.",
    Emp: "Betonend: Betont das abhängige Nomen.",
    Exc: "Ausrufend: Drückt die Überraschung des Sprechers aus.",
    Ind: "Unbestimmte: Bezieht sich auf einen nicht spezifischen Gegenstand.",
    Int: "Interrogativ: Wird in Fragen verwendet.",
    Neg: "Negativ: Drückt die Verneinung aus.",
    Prs: "Personal: Bezieht sich auf eine Person oder Sache.",
    Rcp: "Reziprok: Weist auf eine gegenseitige Handlung oder Beziehung hin.",
    Rel: "Relativ: Einführung einer Relativklausel.",
    Tot: "Total (Kollektiv): Bezieht sich auf eine gesamte Gruppe oder Sammlung.",
  },
  Reflex: {
    Yes: "Ja: Zeigt Reflexivität an.",
  },
  Tense: {
    Fut: "Zukunft: Bezug auf zukünftige Zeit.",
    Past: "Vergangenheit: Bezug auf vergangene Zeit.",
    Pres: "Präsens: Bezug auf gegenwärtige Zeit.",
  },
  VerbForm: {
    Conv: "Konverb: Verbale Form mit adverbialer Funktion.",
    Fin: "Finit: Durch das Subjekt in Person und Anzahl begrenzt.",
    Inf: "Infinitiv: Grundform oder Wurzelform eines Verbs.",
    Part: "Partizip: Verbale Form, die als Adjektiv verwendet wird.",
  },
  Voice: {
    Act: "Aktiv: Subjekt führt die Handlung aus.",
    Antip: "Antipassiv: Betont die Handlung anstelle des Objekts.",
    Cau: "Kausativ: Zeigt eine verursachende oder machende Handlung an.",
    Dir: "Direkt: Direkte Handlung ohne Vermittler.",
    Inv: "Invers: Kehrt die Rollen von Subjekt und Objekt um.",
    Mid: "Mittel: Die Handlung betrifft das Subjekt reflexiv.",
    Pass: "Passiv: Das Subjekt wird von dem Verb beeinflusst.",
    Rcp: "Reziprok: Zeigt eine gegenseitige Handlung oder Beziehung an.",
    Ref: "Reflexiv: Subjekt und Objekt sind identisch.",
    Spont:
      "Spontan: Die Handlung geschieht spontan oder ohne bekannte Ursache.",
  },
  Foreign: {
    Yes: "Fremdwort: Ein Wort aus einer fremden Sprache.",
  },
};

const UniversalFeatures_DESCRIPTION_EN = {
  Animacy: {
    Anim: "Animate: Living beings with self-dynamics.",
    Hum: "Human: Refers to humans.",
    Inan: "Inanimate: Not living, without self-dynamics.",
    Nhum: "Non-human: Not connected with humans.",
  },
  Aspect: {
    Hab: "Habitual: Expresses repeated or habitual actions.",
    Imp: "Imperfect: Ongoing or continuous action.",
    Perf: "Perfect: Completed action with relevance to the present.",
    Prog: "Progressive: Action in progress at a specific time.",
  },
  Case: {
    Abe: "Ablative: Movement away from something.",
    Acc: "Accusative: Direct object of a transitive verb.",
    Erg: "Ergative: Subject of a transitive verb in ergative-absolutive languages.",
    Nom: "Nominative: Subject of a verb.",
    Abs: "Absolutive: Subject of an intransitive verb or direct object of a transitive verb in ergative-absolutive languages.",
    Dat: "Dative: Indirect object of a verb.",
    Gen: "Genitive: Indicates possession or belonging.",
    Ins: "Instrumental: Means through which an action is performed.",
    Loc: "Locative: Location of the action.",
    Par: "Partitive: Part of a whole.",
    Voc: "Vocative: Used for direct address.",
  },
  Definite: {
    Com: "Comitative: In connection or companionship.",
    Cons: "Construct State: Marks a possessed noun in the construct state.",
    Def: "Definite: Specific and identifiable.",
    Ind: "Indefinite: Not specific or identifiable.",
  },
  Degree: {
    Abs: "Absolute: Base form of an adjective or adverb.",
    Cmp: "Comparative: Indicates a higher degree compared to another.",
    Equ: "Equative: Indicates equality.",
    Pos: "Positive: Base form of an adjective or adverb.",
    Sup: "Superlative: Indicates the highest degree.",
  },
  Evident: {
    Fh: "Familiar Tradition: Information from a familiar source.",
    Nfh: "Non-familiar Tradition: Information from an unknown source.",
  },
  Gender: {
    Com: "Common: No specific gender distinction.",
    Fem: "Feminine: The, Female gender.",
    Masc: "Masculine: The, Male gender.",
    Neut: "Neutral: The, No gender or neutral gender.",
  },
  Mood: {
    Cnd: "Conditional: Dependent on a condition.",
    Imp: "Imperative: Command or request.",
    Ind: "Indicative: Statements of facts.",
    Jus: "Jussive: Expresses a mild command or request.",
    Sub: "Subjunctive: Expresses doubt, possibility, necessity, or action contrary to fact.",
  },
  NumType: {
    Card: "Cardinal: Numbers indicating quantity.",
    Dist: "Distributive: Refers to each member in a set.",
    Frac: "Fraction: Numbers indicating a part of a whole.",
    Mult: "Multiplicative: Indicates multiplication.",
    Ord: "Ordinal: Numbers indicating position or order.",
    Range: "Range: Numbers indicating a range of values.",
    Sets: "Sets: Numbers indicating sets of things.",
  },
  Number: {
    Count: "Counting: Singular or plural depending on quantity.",
    Dual: "Dual: Refers to a pair.",
    Grpa: "Greater Paucal: More than a paucal number.",
    Grpl: "Greater Plural: More than a plural.",
    Inv: "Inverse: Indicates the opposite of the standard number.",
    Pauc: "Paucal: Refers to a few.",
    Plur: "Plural: Refers to more than one.",
    Ptan: "Plurale tantum: Used only in the plural form.",
    Sing: "Singular: Refers to one.",
    Tri: "Trial: Refers to three.",
  },
  Person: {
    "0": "Zeroth Person: No participant.",
    "1": "First Person: Speaker or speaker.",
    "2": "Second Person: Listener or audience.",
    "3": "Third Person: Someone or something outside the speaker or listener.",
  },
  Polarity: {
    Neg: "Negative: Indicates negation.",
    Pos: "Positive: Indicates affirmation.",
  },
  Politeness: {
    Elev: "Elevated: Polite or formal language.",
    Form: "Formal: Polite or formal language.",
    Humb: "Humble: Polite or humble language.",
    Infm: "Informal: Informal or casual language.",
  },
  Poss: {
    Yes: "Yes: Indicates possession.",
  },
  PronType: {
    Art: "Article: A type of determiner.",
    Dem: "Demonstrative: Points to or specifies a noun.",
    Emp: "Emphatic: Emphasizes the dependent noun.",
    Exc: "Exclamatory: Expresses the speaker's surprise.",
    Ind: "Indefinite: Refers to a non-specific object.",
    Int: "Interrogative: Used in questions.",
    Neg: "Negative: Expresses negation.",
    Prs: "Personal: Refers to a person or thing.",
    Rcp: "Reciprocal: Points to a mutual action or relationship.",
    Rel: "Relative: Introduces a relative clause.",
    Tot: "Total (Collective): Refers to an entire group or collection.",
  },
  Reflex: {
    Yes: "Yes: Indicates reflexivity.",
  },
  Tense: {
    Fut: "Future: Refers to future time.",
    Past: "Past: Refers to past time.",
    Pres: "Present: Refers to present time.",
  },
  VerbForm: {
    Conv: "Converb: Verbal form with adverbial function.",
    Fin: "Finite: Limited by the subject in person and number.",
    Inf: "Infinitive: Base form or root form of a verb.",
    Part: "Participle: Verbal form used as an adjective.",
  },
  Voice: {
    Act: "Active: Subject performs the action.",
    Antip: "Antipassive: Emphasizes the action instead of the object.",
    Cau: "Causative: Indicates a causing or making action.",
    Dir: "Direct: Direct action without an intermediary.",
    Inv: "Inverse: Reverses the roles of subject and object.",
    Mid: "Middle: The action affects the subject reflexively.",
    Pass: "Passive: The subject is affected by the verb.",
    Rcp: "Reciprocal: Indicates a mutual action or relationship.",
    Ref: "Reflexive: Subject and object are identical.",
    Spont:
      "Spontaneous: The action occurs spontaneously or without a known cause.",
  },
  Foreign: {
    Yes: "Loanword: A word from a foreign language.",
  },
};

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const _available = {
  UniversalFeatures_DESCRIPTION_ES,
  UniversalFeatures_DESCRIPTION_DE,
  UniversalFeatures_DESCRIPTION_EN,
};

export default {
  es: UniversalFeatures_DESCRIPTION_ES,
  de: UniversalFeatures_DESCRIPTION_DE,
  en: UniversalFeatures_DESCRIPTION_EN,
};
